name: Rent Houses

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ['develop']
  push:
    branches: ['develop']

env:
  I18N_PATH: "./apps/rent-houses-i18n"
  TRANSLOCO_PATH: "./apps/rent-houses-transloco"

jobs:
  check-dictionaries-i18n:
    name: Check dictionaries (i18n)
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Check dictionaries
        working-directory: ${{ env.I18N_PATH }}
        run: npm run check:dictionaries

  build-i18n:
    needs: [check-dictionaries-i18n]
    name: Build (i18n)
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ${{ env.I18N_PATH }}
        run: npm ci --ignore-scripts
      - name: Build
        working-directory: ${{ env.I18N_PATH }}
        run: npm run build:localize:all

  check-dictionaries-transloco:
    name: Check dictionaries (transloco)
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Check dictionaries
        working-directory: ./apps/rent-houses-transloco
        run: npm run check:dictionaries

  build-transloco:
    needs: [check-dictionaries-transloco]
    name: Build (transloco)
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ${{ env.TRANSLOCO_PATH }}
        run: npm ci --ignore-scripts
      - name: Build
        working-directory: ${{ env.TRANSLOCO_PATH }}
        run: npm run build
